routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/catalogue-public', 'CataloguePublicController@index');

// GET /reserver
Route::get('reserver', 'ReserverController@index');

// POST /reserver
Route::post('reserver', 'ReserverController@post');

// Administration

Route::get('/admin', 'AdminController@index');

Route::get('/admin', 'AdminController@index')->name('admin');


Route::resource('catalogues', 'CatalogueAdminController');  // create, read, update, delete

Route::resource('clients', 'UserAdminController');  // create, read, update, delete

Route::resource('reservations', 'ReservationsAdminController');  // create, read, update, delete

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Client
    </h1>
</section>
<div class="content">
    @include('adminlte-templates::common.errors')
    <div class="box box-primary">

        <div class="box-body">
            <div class="row">
                {!! Form::open(['route' => 'clients.store']) !!}

                @include('clients.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Client
    </h1>
</section>
<div class="content">
    @include('adminlte-templates::common.errors')
    <div class="box box-primary">
        <div class="box-body">
            <div class="row">
                {!! Form::model($client, ['route' => ['clients.update', $client->id], 'method' => 'patch']) !!}

                @include('clients.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clients/fields.blade.php
<!-- Nom Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nom:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Mobile Field -->
<div class="form-group col-sm-6">
    {!! Form::label('mobile', 'Mobile:') !!}
    {!! Form::text('mobile', null, ['class' => 'form-control']) !!}
</div>

<!-- Pays Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pays', 'Pays:') !!}
    {!! Form::text('pays', null, ['class' => 'form-control']) !!}
</div>

<!-- Pwd Field -->
<div class="form-group col-sm-6">
    {!! Form::label('password', 'Password:') !!}
    {!! Form::password('password', ['class' => 'form-control']) !!}
</div>

<!-- Admin Field -->
<div class="form-group col-sm-6">
    {!! Form::label('admin', 'Admin:') !!}
    {!! Form::checkbox('admin', false) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('clients.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1 class="pull-left">Clients</h1>
    <h1 class="pull-right">
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
           href="{!! route('clients.create') !!}">Add New</a>
    </h1>
</section>
<div class="content">
    <div class="clearfix"></div>

    @include('flash::message')

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-body">
            @include('clients.table')
        </div>
    </div>
</div>
@endsection

resources/views/clients/show.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Client
    </h1>
</section>
<div class="content">
    <div class="box box-primary">
        <div class="box-body">
            <div class="row" style="padding-left: 20px">
                @include('clients.show_fields')
                <a href="{!! route('clients.index') !!}" class="btn btn-default">Back</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clients/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $client->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $client->name !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $client->email !!}</p>
</div>

<!-- Mobile Field -->
<div class="form-group">
    {!! Form::label('mobile', 'Mobile:') !!}
    <p>{!! $client->mobile !!}</p>
</div>

<!-- Pays Field -->
<div class="form-group">
    {!! Form::label('pays', 'Pays:') !!}
    <p>{!! $client->pays !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $client->created_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $client->deleted_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $client->updated_at !!}</p>
</div>

resources/views/clients/table.blade.php
<table class="table table-responsive" id="clients-table">
    <thead>
    <th>Nom</th>
    <th>Email</th>
    <th>Mobile</th>
    <th>Pays</th>
    <th>Admin</th>
    <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($clients as $client)
    <tr>
        <td>{!! $client->name !!}</td>
        <td>{!! $client->email !!}</td>
        <td>{!! $client->mobile !!}</td>
        <td>{!! $client->pays !!}</td>
        <td>{!! $client->admin !!}</td>
        <td>
            {!! Form::open(['route' => ['clients.destroy', $client->id], 'method' => 'delete']) !!}
            <div class='btn-group'>
                <a href="{!! route('clients.show', [$client->id]) !!}" class='btn btn-default btn-xs'><i
                            class="glyphicon glyphicon-eye-open"></i></a>
                <a href="{!! route('clients.edit', [$client->id]) !!}" class='btn btn-default btn-xs'><i
                            class="glyphicon glyphicon-edit"></i></a>
                {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn
                btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
            </div>
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
    </tbody>
</table>