routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/catalogue-public', 'CataloguePublicController@index');

// GET /reserver
Route::get('reserver', 'ReserverController@index');

// POST /reserver
Route::post('reserver', 'ReserverController@post');

// Administration

Route::get('/admin', 'AdminController@index');

Route::get('/admin', 'AdminController@index')->name('admin');


Route::resource('catalogues', 'CatalogueAdminController');  // create, read, update, delete

Route::resource('clients', 'UserAdminController');  // create, read, update, delete

Route::resource('reservations', 'ReservationsAdminController');  // create, read, update, delete

app/Models/Catalogue.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Catalogue
 * @package App\Models
 * @version March 22, 2018, 3:37 pm UTC
 */
class Catalogue extends Model
{
    use SoftDeletes;

    public $table = 'catalogue';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'numero',
        'capacite',
        'type',
        'description',
        'prix'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'numero' => 'integer',
        'capacite' => 'integer',
        'type' => 'string',
        'description' => 'string',
        'prix' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function reservations()
    {
        return $this->hasMany(\App\Models\Reservation::class);
    }
}

resources/views/catalogues/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Catalogue
    </h1>
</section>
<div class="content">
    @include('adminlte-templates::common.errors')
    <div class="box box-primary">

        <div class="box-body">
            <div class="row">
                {!! Form::open(['route' => 'catalogues.store']) !!}

                @include('catalogues.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/catalogues/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Catalogue
    </h1>
</section>
<div class="content">
    @include('adminlte-templates::common.errors')
    <div class="box box-primary">
        <div class="box-body">
            <div class="row">
                {!! Form::model($catalogue, ['route' => ['catalogues.update', $catalogue->id], 'method' => 'patch']) !!}

                @include('catalogues.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/catalogues/fields.blade.php
<!-- Numero Field -->
<div class="form-group col-sm-6">
    {!! Form::label('numero', 'Numero:') !!}
    {!! Form::number('numero', null, ['class' => 'form-control']) !!}
</div>

<!-- Capacite Field -->
<div class="form-group col-sm-6">
    {!! Form::label('capacite', 'Capacite:') !!}
    {!! Form::number('capacite', null, ['class' => 'form-control']) !!}
</div>

<!-- Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', 'Type:') !!}
    {!! Form::text('type', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Prix Field -->
<div class="form-group col-sm-6">
    {!! Form::label('prix', 'Prix:') !!}
    {!! Form::number('prix', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('catalogues.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/catalogues/index.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1 class="pull-left">Catalogues</h1>
    <h1 class="pull-right">
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
           href="{!! route('catalogues.create') !!}">Add New</a>
    </h1>
</section>
<div class="content">
    <div class="clearfix"></div>

    @include('flash::message')

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-body">
            @include('catalogues.table')
        </div>
    </div>
</div>
@endsection

resources/views/catalogues/show.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Catalogue
    </h1>
</section>
<div class="content">
    <div class="box box-primary">
        <div class="box-body">
            <div class="row" style="padding-left: 20px">
                @include('catalogues.show_fields')
                <a href="{!! route('catalogues.index') !!}" class="btn btn-default">Back</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/catalogues/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $catalogue->id !!}</p>
</div>

<!-- Numero Field -->
<div class="form-group">
    {!! Form::label('numero', 'Numero:') !!}
    <p>{!! $catalogue->numero !!}</p>
</div>

<!-- Capacite Field -->
<div class="form-group">
    {!! Form::label('capacite', 'Capacite:') !!}
    <p>{!! $catalogue->capacite !!}</p>
</div>

<!-- Type Field -->
<div class="form-group">
    {!! Form::label('type', 'Type:') !!}
    <p>{!! $catalogue->type !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $catalogue->description !!}</p>
</div>

<!-- Prix Field -->
<div class="form-group">
    {!! Form::label('prix', 'Prix:') !!}
    <p>{!! $catalogue->prix !!}</p>
</div>

resources/views/catalogues/table.blade.php
<table class="table table-responsive" id="catalogues-table">
    <thead>
    <th>Numero</th>
    <th>Capacite</th>
    <th>Type</th>
    <th>Description</th>
    <th>Prix</th>
    <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($catalogues as $catalogue)
    <tr>
        <td>{!! $catalogue->numero !!}</td>
        <td>{!! $catalogue->capacite !!}</td>
        <td>{!! $catalogue->type !!}</td>
        <td>{!! $catalogue->description !!}</td>
        <td>{!! $catalogue->prix !!}</td>
        <td>
            {!! Form::open(['route' => ['catalogues.destroy', $catalogue->id], 'method' => 'delete']) !!}
            <div class='btn-group'>
                <a href="{!! route('catalogues.show', [$catalogue->id]) !!}" class='btn btn-default btn-xs'><i
                            class="glyphicon glyphicon-eye-open"></i></a>
                <a href="{!! route('catalogues.edit', [$catalogue->id]) !!}" class='btn btn-default btn-xs'><i
                            class="glyphicon glyphicon-edit"></i></a>
                {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn
                btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
            </div>
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
    </tbody>
</table>