routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/catalogue-public', 'CataloguePublicController@index');

// GET /reserver
Route::get('reserver', 'ReserverController@index');

// POST /reserver
Route::post('reserver', 'ReserverController@post');

// Administration

Route::get('/admin', 'AdminController@index');

Route::get('/admin', 'AdminController@index')->name('admin');


Route::resource('catalogues', 'CatalogueAdminController');  // create, read, update, delete

Route::resource('clients', 'UserAdminController');  // create, read, update, delete

Route::resource('reservations', 'ReservationsAdminController');  // create, read, update, delete

app/Models/Reservations.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Reservations
 * @package App\Models
 * @version March 22, 2018, 4:27 pm UTC
 */
class Reservations extends Model
{
    use SoftDeletes;

    public $table = 'reservations';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'arrivee',
        'depart',
        'prix',
        'catalogue_id',
        'user_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'arrivee' => 'date',
        'depart' => 'date',
        'prix' => 'integer',
        'catalogue_id' => 'integer',
        'user_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function catalogue()
    {
        return $this->belongsTo(\App\Models\Catalogue::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function user()
    {
        return $this->belongsTo(\App\User::class);
    }
}

resources/views/reservations/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Reservations
    </h1>
</section>
<div class="content">
    @include('adminlte-templates::common.errors')
    <div class="box box-primary">

        <div class="box-body">
            <div class="row">
                {!! Form::open(['route' => 'reservations.store']) !!}

                @include('reservations.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/reservations/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Reservations
    </h1>
</section>
<div class="content">
    @include('adminlte-templates::common.errors')
    <div class="box box-primary">
        <div class="box-body">
            <div class="row">
                {!! Form::model($reservations, ['route' => ['reservations.update', $reservations->id], 'method' =>
                'patch']) !!}

                @include('reservations.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/reservations/fields.blade.php
<!-- Arrivee Field -->
<div class="form-group col-sm-6">
    {!! Form::label('arrivee', 'Arrivee:') !!}
    {!! Form::date('arrivee', null, ['class' => 'form-control']) !!}
</div>

<!-- Depart Field -->
<div class="form-group col-sm-6">
    {!! Form::label('depart', 'Depart:') !!}
    {!! Form::date('depart', null, ['class' => 'form-control']) !!}
</div>

<!-- Prix Field -->
<div class="form-group col-sm-6">
    {!! Form::label('prix', 'Prix:') !!}
    {!! Form::number('prix', null, ['class' => 'form-control']) !!}
</div>

<!-- Catalogue Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('catalogue_id', 'Catalogue Id:') !!}
    {!! Form::number('catalogue_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Client Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'Client Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('reservations.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/reservations/index.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1 class="pull-left">Reservations</h1>
    <h1 class="pull-right">
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
           href="{!! route('reservations.create') !!}">Add New</a>
    </h1>
</section>
<div class="content">
    <div class="clearfix"></div>

    @include('flash::message')

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-body">
            @include('reservations.table')
        </div>
    </div>
</div>
@endsection

resources/views/reservations/show.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Reservations
    </h1>
</section>
<div class="content">
    <div class="box box-primary">
        <div class="box-body">
            <div class="row" style="padding-left: 20px">
                @include('reservations.show_fields')
                <a href="{!! route('reservations.index') !!}" class="btn btn-default">Back</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/reservations/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $reservations->id !!}</p>
</div>

<!-- Arrivee Field -->
<div class="form-group">
    {!! Form::label('arrivee', 'Arrivee:') !!}
    <p>{!! $reservations->arrivee !!}</p>
</div>

<!-- Depart Field -->
<div class="form-group">
    {!! Form::label('depart', 'Depart:') !!}
    <p>{!! $reservations->depart !!}</p>
</div>

<!-- Prix Field -->
<div class="form-group">
    {!! Form::label('prix', 'Prix:') !!}
    <p>{!! $reservations->prix !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $reservations->created_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $reservations->deleted_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $reservations->updated_at !!}</p>
</div>

<!-- Catalogue Id Field -->
<div class="form-group">
    {!! Form::label('catalogue_id', 'Catalogue Id:') !!}
    <p>{!! $reservations->catalogue_id !!}</p>
</div>

<!-- Client Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'Client Id:') !!}
    <p>{!! $reservations->user_id !!}</p>
</div>

resources/views/reservations/table.blade.php
<table class="table table-responsive" id="reservations-table">
    <thead>
    <th>Client Id</th>
    <th>Arrivee</th>
    <th>Depart</th>
    <th>Prix</th>
    <th>Réservation</th>
    <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($reservations as $reservations)
    <tr>
        <td>#{!! $reservations->user_id !!} {!! $reservations->user->name !!}</td>
        <td>{!! $reservations->arrivee !!}</td>
        <td>{!! $reservations->depart !!}</td>
        <td>{!! $reservations->prix !!}</td>
        <td>{!! $reservations->catalogue->type !!} {!! $reservations->catalogue->numero !!}</td>

        <td>
            {!! Form::open(['route' => ['reservations.destroy', $reservations->id], 'method' => 'delete']) !!}
            <div class='btn-group'>
                <a href="{!! route('reservations.show', [$reservations->id]) !!}" class='btn btn-default btn-xs'><i
                            class="glyphicon glyphicon-eye-open"></i></a>
                <a href="{!! route('reservations.edit', [$reservations->id]) !!}" class='btn btn-default btn-xs'><i
                            class="glyphicon glyphicon-edit"></i></a>
                {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn
                btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
            </div>
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
    </tbody>
</table>